services:
  web:
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_HOST: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password0123blue
      POSTGRES_DB: rails7_tutorial_development
    restart: always
    tty: true
    stdin_open: true
    depends_on:
      - database


  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password0123blue
      POSTGRES_DB: rails7_tutorial_development
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_volume:

